/**
 * Centralized API endpoints for the PointTrack application.
 * Following "CÁCH A": baseURL is the host, and endpoints include the full path starting with /api/v1.
 */

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/v1/auth/login',
    LOGOUT: '/api/v1/auth/logout',
    ME: '/api/v1/auth/me',
    REFRESH: '/api/v1/auth/token/refresh',
    PROFILE: '/api/v1/auth/profile',
    CHANGE_PASSWORD: '/api/v1/auth/password/change',
    FIRST_CHANGE_PASSWORD: '/api/v1/auth/password/first-change',
    FORGOT_PASSWORD: '/api/v1/auth/password/forgot',
    RESET_PASSWORD: '/api/v1/auth/password/reset',
    VERIFY_OTP: '/api/v1/auth/password/verify-otp',
    ACCOUNTS: '/api/v1/auth/accounts',
  },
  EMPLOYEES: {
    LIST: '/api/v1/employees',
    LIST_ALL: '/api/v1/employees/list-all',
    CREATE: '/api/v1/employees',
    DETAIL: (id: string | number) => `/api/v1/employees/${id}`,
    UPDATE: (id: string | number) => `/api/v1/employees/${id}`,
    DELETE: (id: string | number) => `/api/v1/employees/${id}`,
    IMPORT: '/api/v1/employees/import',
    IMPORT_TEMPLATE: '/api/v1/employees/import/template',
    ME: '/api/v1/employees/me',
    STATISTICS: '/api/v1/employees/statistics',
    STATS: '/api/v1/employees/stats',
    UPDATE_STATUS: (id: string | number) => `/api/v1/employees/${id}/status`,
    UPDATE_SALARY_LEVEL: (id: string | number) => `/api/v1/employees/${id}/salary-level`,
    SALARY_HISTORY: (id: string | number) => `/api/v1/employees/${id}/salary-history`,
  },
  ATTENDANCE: {
    CHECK_IN: '/api/v1/attendance/check-in',
    CHECK_OUT: '/api/v1/attendance/check-out',
    HISTORY: '/api/v1/attendance/history',
    MY_RECORDS: '/api/v1/attendance/my-records',
    LOCATIONS: '/api/v1/attendance/locations',
    RECORDS: '/api/v1/attendance/records',
    EXPORT: '/api/v1/attendance/export',
    EXPLANATIONS: '/api/v1/attendance/explanations',
    APPROVE_EXPLANATION: (id: string | number) => `/api/v1/attendance/explanations/${id}/approve`,
    REJECT_EXPLANATION: (id: string | number) => `/api/v1/attendance/explanations/${id}/reject`,
    UPDATE_NOTE: (id: string | number) => `/api/v1/attendance/${id}/note`,
    ADMIN_UPDATE: (recordId: string | number) => `/api/v1/attendance/${recordId}/admin-update`,
    SCHEDULE_CREATE: '/api/v1/attendance/schedule/create',
    SCHEDULE_ALL: '/api/v1/attendance/schedule/all',
  },
  ATTENDANCE_HISTORY: {
    HISTORY: '/api/v1/attendance-history/history',
    LOCATIONS: '/api/v1/attendance-history/locations',
    UPDATE_NOTE: (id: string | number) => `/api/v1/attendance-history/${id}/note`,
    EXPORT: '/api/v1/attendance-history/export',
  },
  CUSTOMERS: {
    LIST: '/api/v1/customers',
    CREATE: '/api/v1/customers',
    DETAIL: (id: string | number) => `/api/v1/customers/${id}`,
    UPDATE: (id: string | number) => `/api/v1/customers/${id}`,
    DELETE: (id: string | number) => `/api/v1/customers/${id}`,
    ACTIVE_WITH_GPS: '/api/v1/customers/active-with-gps',
    EXPORT: '/api/v1/customers/export',
    IMPORT: '/api/v1/customers/import',
    IMPORT_TEMPLATE: '/api/v1/customers/import/template',
    GEOCODE: (id: string | number) => `/api/v1/customers/${id}/geocode`,
    UPDATE_GPS: (id: string | number) => `/api/v1/customers/${id}/gps`,
  },
  SHIFTS: {
    LIST: '/api/v1/shifts',
    CREATE: '/api/v1/shifts',
    DETAIL: (id: string | number) => `/api/v1/shifts/${id}`,
    UPDATE: (id: string | number) => `/api/v1/shifts/${id}`,
    DELETE: (id: string | number) => `/api/v1/shifts/${id}`,
    DELETE_HARD: (id: string | number) => `/api/v1/shifts/${id}/hard`,
    ASSIGN: '/api/v1/shifts/assign',
    UPDATE_ASSIGN: (shiftId: string | number) => `/api/v1/shifts/${shiftId}/assign`,
    UNASSIGN: (id: string | number) => `/api/v1/shifts/${id}/assign`,
    CHECK_IN: (id: string | number) => `/api/v1/shifts/${id}/check-in`,
    CHECK_OUT: (id: string | number) => `/api/v1/shifts/${id}/check-out`,
    CLAIM: (id: string | number) => `/api/v1/shifts/${id}/claim`,
    CONFIRM: (id: string | number) => `/api/v1/shifts/${id}/confirm`,
    MY_TODAY: '/api/v1/shifts/my-today',
    OPEN: '/api/v1/shifts/open',
    AVAILABLE_EMPLOYEES: '/api/v1/shifts/available-employees',
    CONFLICT_CHECK: '/api/v1/shifts/conflict-check',
    COPY_WEEK: '/api/v1/shifts/copy-week',
    RECURRING: '/api/v1/shifts/recurring',
  },
  SHIFT_SWAP: {
    LIST: '/api/v1/shift-swap',
    CREATE: '/api/v1/shift-swap',
    DETAIL: (id: string | number) => `/api/v1/shift-swap/${id}`,
    DELETE: (id: string | number) => `/api/v1/shift-swap/${id}`,
    APPROVE: (id: string | number) => `/api/v1/shift-swap/${id}/approve`,
    REJECT: (id: string | number) => `/api/v1/shift-swap/${id}/reject`,
    RESPOND: (id: string | number) => `/api/v1/shift-swap/${id}/respond`,
    AVAILABLE_EMPLOYEES: '/api/v1/shift-swap/available-employees',
    AVAILABLE_SHIFTS: '/api/v1/shift-swap/available-shifts',
  },
  SALARY_LEVELS: {
    LIST: '/api/v1/salary-levels',
    CREATE: '/api/v1/salary-levels',
    DETAIL: (id: string | number) => `/api/v1/salary-levels/${id}`,
    UPDATE: (id: string | number) => `/api/v1/salary-levels/${id}`,
    DELETE: (id: string | number) => `/api/v1/salary-levels/${id}`,
  },
  SCHEDULING_SETTINGS: {
    GET: '/api/v1/scheduling/settings',
    UPDATE_GRACE_PERIOD: '/api/v1/scheduling/settings/grace-period',
    UPDATE_PENALTY_RULES: '/api/v1/scheduling/settings/penalty-rules',
    UPDATE_TRAVEL_BUFFER: '/api/v1/scheduling/settings/travel-buffer',
  },
  FILES: {
    UPLOAD: '/api/v1/files/upload',
    DOWNLOAD: '/api/v1/files/download',
    TMP_UPLOAD: '/api/v1/tmpUpload',
  },
  SHIFT_TEMPLATES: {
    LIST: '/api/v1/shift-templates',
    CREATE: '/api/v1/shift-templates',
    UPDATE: (id: string | number) => `/api/v1/shift-templates/${id}`,
    DELETE: (id: string | number) => `/api/v1/shift-templates/${id}`,
  },
  PACKAGES: {
    LIST: '/api/v1/packages',
    CREATE: '/api/v1/packages',
    DETAIL: (id: string | number) => `/api/v1/packages/${id}`,
    CANCEL: (id: string | number) => `/api/v1/packages/${id}/cancel`,
    UPDATE_EMPLOYEE: (id: string | number) => `/api/v1/packages/${id}/employee`,
  },
  USER: {
    SIGNUP: '/api/v1/user/signup',
    PROFILE: (id: string | number) => `/api/v1/user/profile/${id}`,
    SAVE_EDIT: '/api/v1/user/saveEdit',
    EDIT_PROFILE: '/api/v1/user/edit-profile',
    CHANGE_PASSWORD: '/api/v1/user/change-password',
    ADDRESS: '/api/v1/user/address',
    ADD_ADDRESS: '/api/v1/user/address/add',
    UPDATE_ADDRESS: (id: string | number) => `/api/v1/user/address/${id}`,
    DELETE_ADDRESS: (id: string | number) => `/api/v1/user/address/${id}`,
    SET_DEFAULT_ADDRESS: (id: string | number) => `/api/v1/user/address/${id}/set-default`,
    GET_ALL: '/api/v1/user/getAll',
    UPLOAD_AVATAR: '/api/v1/user/upload-avatar',
  }
};
